docs:
- changed-files:
  - any-glob-to-any-file:
    - docs/**
    - README.md

automation:
- changed-files:
  - any-glob-to-any-file:
    - .github/**
    - .pre-commit-config.yaml
    - scripts/**
    - .spacelift/**

src:
- changed-files:
  - any-glob-to-any-file:
    - ./*.tf
